//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoottoriV1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MalliE25Riasetus
    {
        public int AsetusID { get; set; }
        public int RoottoriID { get; set; }
        public int KoneID { get; set; }
        public int LeukaID { get; set; }
        public int KarkiID { get; set; }
        public int MagneettiID { get; set; }
        public int PalettiID { get; set; }
        public int PiirustusID { get; set; }
    
        public virtual Karjet Karjet { get; set; }
        public virtual Koneet Koneet { get; set; }
        public virtual Leuat Leuat { get; set; }
        public virtual Magneetit Magneetit { get; set; }
        public virtual Paletit Paletit { get; set; }
        public virtual Piirustukset Piirustukset { get; set; }
        public virtual Roottorit Roottorit { get; set; }
    }
}
