//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoottoriV1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roottorit
    {
        public int RoottoriID { get; set; }
        public string Malli { get; set; }
        public string RaakaAine { get; set; }
        public string Pituus { get; set; }
        public string Halkaisija { get; set; }
        public string Kiinnityspinta { get; set; }
        public string OhjNrot { get; set; }
        public int KoneID { get; set; }
        public Nullable<int> KarkiID { get; set; }
        public Nullable<int> LeukaID { get; set; }
        public Nullable<int> MagneettiID { get; set; }
        public Nullable<int> PalettiID { get; set; }
        public Nullable<int> PiirustusID { get; set; }
    
        public virtual Koneet Koneet { get; set; }
        public virtual Karjet Karjet { get; set; }
        public virtual Leuat Leuat { get; set; }
        public virtual Magneetit Magneetit { get; set; }
        public virtual Paletit Paletit { get; set; }
        public virtual Piirustukset Piirustukset { get; set; }
    }
}
