//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoottoriV1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viestit
    {
        public int ViestiId { get; set; }
        public string Sisalto { get; set; }
        public string Lahettaja { get; set; }
        public Nullable<System.DateTime> Aika { get; set; }
        public int Luettu { get; set; }
    }
}
